### ISSUE TITLE
Part 2.4: error in statefulset.yaml example

### ISSUE THREAD

**Issue by markku63** [kubernetes-hy/kubernetes-hy.github.io#39]
The Service part of the file has an error: the selector must match the label of the pod or DNS resolution won't work.
```
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: web
  clusterIP: None
  selector:
    app: redisapp
```
